// @generated by protoc-gen-connect-query v2.1.0 with parameter "target=ts"
// @generated from file api/v1/api.proto (package api.v1, syntax proto3)
/* eslint-disable */

import { Service } from "./api_pb";

/**
 * @generated from rpc api.v1.Service.CreateJobApplication
 */
export const createJobApplication = Service.method.createJobApplication;

/**
 * @generated from rpc api.v1.Service.ListJobApplications
 */
export const listJobApplications = Service.method.listJobApplications;

/**
 * @generated from rpc api.v1.Service.UpdateJobApplication
 */
export const updateJobApplication = Service.method.updateJobApplication;

/**
 * @generated from rpc api.v1.Service.DeleteJobApplication
 */
export const deleteJobApplication = Service.method.deleteJobApplication;
