// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file api/v1/api.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/api.proto.
 */
export const file_api_v1_api: GenFile = /*@__PURE__*/
  fileDesc("ChBhcGkvdjEvYXBpLnByb3RvEgZhcGkudjEi+wEKG0NyZWF0ZUpvYkFwcGxpY2F0aW9uUmVxdWVzdBIPCgdjb21wYW55GAEgASgJEg0KBXRpdGxlGAIgASgJEjEKC2Rlc2NyaXB0aW9uGAMgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEisKBW5vdGVzGAQgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEigKAmN2GAUgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjIKDGNvdmVyX2xldHRlchgGIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZSJPChxDcmVhdGVKb2JBcHBsaWNhdGlvblJlc3BvbnNlEi8KD2pvYl9hcHBsaWNhdGlvbhgBIAEoCzIWLmFwaS52MS5Kb2JBcHBsaWNhdGlvbiLaAgoOSm9iQXBwbGljYXRpb24SCgoCaWQYASABKAkSDwoHY29tcGFueRgCIAEoCRINCgV0aXRsZRgDIAEoCRIxCgtkZXNjcmlwdGlvbhgEIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIrCgVub3RlcxgFIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIoCgJjdhgGIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIyCgxjb3Zlcl9sZXR0ZXIYByABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSLgoKY3JlYXRlZF9hdBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAybAoHU2VydmljZRJhChRDcmVhdGVKb2JBcHBsaWNhdGlvbhIjLmFwaS52MS5DcmVhdGVKb2JBcHBsaWNhdGlvblJlcXVlc3QaJC5hcGkudjEuQ3JlYXRlSm9iQXBwbGljYXRpb25SZXNwb25zZUITWhFraXNla2kvYXBpL3YxO2FwaWIGcHJvdG8z", [file_google_protobuf_timestamp, file_google_protobuf_wrappers]);

/**
 * @generated from message api.v1.CreateJobApplicationRequest
 */
export type CreateJobApplicationRequest = Message<"api.v1.CreateJobApplicationRequest"> & {
  /**
   * @generated from field: string company = 1;
   */
  company: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: google.protobuf.StringValue description = 3;
   */
  description?: string;

  /**
   * @generated from field: google.protobuf.StringValue notes = 4;
   */
  notes?: string;

  /**
   * @generated from field: google.protobuf.StringValue cv = 5;
   */
  cv?: string;

  /**
   * @generated from field: google.protobuf.StringValue cover_letter = 6;
   */
  coverLetter?: string;
};

/**
 * Describes the message api.v1.CreateJobApplicationRequest.
 * Use `create(CreateJobApplicationRequestSchema)` to create a new message.
 */
export const CreateJobApplicationRequestSchema: GenMessage<CreateJobApplicationRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_api, 0);

/**
 * @generated from message api.v1.CreateJobApplicationResponse
 */
export type CreateJobApplicationResponse = Message<"api.v1.CreateJobApplicationResponse"> & {
  /**
   * @generated from field: api.v1.JobApplication job_application = 1;
   */
  jobApplication?: JobApplication;
};

/**
 * Describes the message api.v1.CreateJobApplicationResponse.
 * Use `create(CreateJobApplicationResponseSchema)` to create a new message.
 */
export const CreateJobApplicationResponseSchema: GenMessage<CreateJobApplicationResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_api, 1);

/**
 * @generated from message api.v1.JobApplication
 */
export type JobApplication = Message<"api.v1.JobApplication"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string company = 2;
   */
  company: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: google.protobuf.StringValue description = 4;
   */
  description?: string;

  /**
   * @generated from field: google.protobuf.StringValue notes = 5;
   */
  notes?: string;

  /**
   * @generated from field: google.protobuf.StringValue cv = 6;
   */
  cv?: string;

  /**
   * @generated from field: google.protobuf.StringValue cover_letter = 7;
   */
  coverLetter?: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message api.v1.JobApplication.
 * Use `create(JobApplicationSchema)` to create a new message.
 */
export const JobApplicationSchema: GenMessage<JobApplication> = /*@__PURE__*/
  messageDesc(file_api_v1_api, 2);

/**
 * @generated from service api.v1.Service
 */
export const Service: GenService<{
  /**
   * @generated from rpc api.v1.Service.CreateJobApplication
   */
  createJobApplication: {
    methodKind: "unary";
    input: typeof CreateJobApplicationRequestSchema;
    output: typeof CreateJobApplicationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_api, 0);

