// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v1/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobApplicationStatus int32

const (
	JobApplicationStatus_JOB_APPLICATION_STATUS_UNSPECIFIED JobApplicationStatus = 0
	JobApplicationStatus_JOB_APPLICATION_STATUS_APPLIED     JobApplicationStatus = 1
	JobApplicationStatus_JOB_APPLICATION_STATUS_SCREENING   JobApplicationStatus = 2
	JobApplicationStatus_JOB_APPLICATION_STATUS_INTERVIEW   JobApplicationStatus = 3
	JobApplicationStatus_JOB_APPLICATION_STATUS_OFFER       JobApplicationStatus = 4
	JobApplicationStatus_JOB_APPLICATION_STATUS_REJECTED    JobApplicationStatus = 5
	JobApplicationStatus_JOB_APPLICATION_STATUS_WITHDRAWN   JobApplicationStatus = 6
	JobApplicationStatus_JOB_APPLICATION_STATUS_ACCEPTED    JobApplicationStatus = 7
)

// Enum value maps for JobApplicationStatus.
var (
	JobApplicationStatus_name = map[int32]string{
		0: "JOB_APPLICATION_STATUS_UNSPECIFIED",
		1: "JOB_APPLICATION_STATUS_APPLIED",
		2: "JOB_APPLICATION_STATUS_SCREENING",
		3: "JOB_APPLICATION_STATUS_INTERVIEW",
		4: "JOB_APPLICATION_STATUS_OFFER",
		5: "JOB_APPLICATION_STATUS_REJECTED",
		6: "JOB_APPLICATION_STATUS_WITHDRAWN",
		7: "JOB_APPLICATION_STATUS_ACCEPTED",
	}
	JobApplicationStatus_value = map[string]int32{
		"JOB_APPLICATION_STATUS_UNSPECIFIED": 0,
		"JOB_APPLICATION_STATUS_APPLIED":     1,
		"JOB_APPLICATION_STATUS_SCREENING":   2,
		"JOB_APPLICATION_STATUS_INTERVIEW":   3,
		"JOB_APPLICATION_STATUS_OFFER":       4,
		"JOB_APPLICATION_STATUS_REJECTED":    5,
		"JOB_APPLICATION_STATUS_WITHDRAWN":   6,
		"JOB_APPLICATION_STATUS_ACCEPTED":    7,
	}
)

func (x JobApplicationStatus) Enum() *JobApplicationStatus {
	p := new(JobApplicationStatus)
	*p = x
	return p
}

func (x JobApplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobApplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_api_proto_enumTypes[0].Descriptor()
}

func (JobApplicationStatus) Type() protoreflect.EnumType {
	return &file_api_v1_api_proto_enumTypes[0]
}

func (x JobApplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobApplicationStatus.Descriptor instead.
func (JobApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{0}
}

type CreateJobApplicationRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Company       string                  `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Notes         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	Cv            *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=cv,proto3" json:"cv,omitempty"`
	CoverLetter   *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	AppliedOn     *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=applied_on,json=appliedOn,proto3" json:"applied_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobApplicationRequest) Reset() {
	*x = CreateJobApplicationRequest{}
	mi := &file_api_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobApplicationRequest) ProtoMessage() {}

func (x *CreateJobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateJobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobApplicationRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateJobApplicationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateJobApplicationRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *CreateJobApplicationRequest) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *CreateJobApplicationRequest) GetCv() *wrapperspb.StringValue {
	if x != nil {
		return x.Cv
	}
	return nil
}

func (x *CreateJobApplicationRequest) GetCoverLetter() *wrapperspb.StringValue {
	if x != nil {
		return x.CoverLetter
	}
	return nil
}

func (x *CreateJobApplicationRequest) GetAppliedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.AppliedOn
	}
	return nil
}

type CreateJobApplicationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobApplication *JobApplication        `protobuf:"bytes,1,opt,name=job_application,json=jobApplication,proto3" json:"job_application,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateJobApplicationResponse) Reset() {
	*x = CreateJobApplicationResponse{}
	mi := &file_api_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobApplicationResponse) ProtoMessage() {}

func (x *CreateJobApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateJobApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobApplicationResponse) GetJobApplication() *JobApplication {
	if x != nil {
		return x.JobApplication
	}
	return nil
}

type ListJobApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobApplicationsRequest) Reset() {
	*x = ListJobApplicationsRequest{}
	mi := &file_api_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobApplicationsRequest) ProtoMessage() {}

func (x *ListJobApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListJobApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{2}
}

type ListJobApplicationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobApplications []*JobApplication      `protobuf:"bytes,1,rep,name=job_applications,json=jobApplications,proto3" json:"job_applications,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListJobApplicationsResponse) Reset() {
	*x = ListJobApplicationsResponse{}
	mi := &file_api_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobApplicationsResponse) ProtoMessage() {}

func (x *ListJobApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListJobApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListJobApplicationsResponse) GetJobApplications() []*JobApplication {
	if x != nil {
		return x.JobApplications
	}
	return nil
}

type UpdateJobApplicationRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Company       string                  `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Title         string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Notes         *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	Cv            *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=cv,proto3" json:"cv,omitempty"`
	CoverLetter   *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	Status        JobApplicationStatus    `protobuf:"varint,8,opt,name=status,proto3,enum=api.v1.JobApplicationStatus" json:"status,omitempty"`
	AppliedOn     *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=applied_on,json=appliedOn,proto3" json:"applied_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobApplicationRequest) Reset() {
	*x = UpdateJobApplicationRequest{}
	mi := &file_api_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobApplicationRequest) ProtoMessage() {}

func (x *UpdateJobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateJobApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateJobApplicationRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateJobApplicationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateJobApplicationRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateJobApplicationRequest) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *UpdateJobApplicationRequest) GetCv() *wrapperspb.StringValue {
	if x != nil {
		return x.Cv
	}
	return nil
}

func (x *UpdateJobApplicationRequest) GetCoverLetter() *wrapperspb.StringValue {
	if x != nil {
		return x.CoverLetter
	}
	return nil
}

func (x *UpdateJobApplicationRequest) GetStatus() JobApplicationStatus {
	if x != nil {
		return x.Status
	}
	return JobApplicationStatus_JOB_APPLICATION_STATUS_UNSPECIFIED
}

func (x *UpdateJobApplicationRequest) GetAppliedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.AppliedOn
	}
	return nil
}

type UpdateJobApplicationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobApplication *JobApplication        `protobuf:"bytes,1,opt,name=job_application,json=jobApplication,proto3" json:"job_application,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateJobApplicationResponse) Reset() {
	*x = UpdateJobApplicationResponse{}
	mi := &file_api_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobApplicationResponse) ProtoMessage() {}

func (x *UpdateJobApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobApplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateJobApplicationResponse) GetJobApplication() *JobApplication {
	if x != nil {
		return x.JobApplication
	}
	return nil
}

type DeleteJobApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobApplicationRequest) Reset() {
	*x = DeleteJobApplicationRequest{}
	mi := &file_api_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobApplicationRequest) ProtoMessage() {}

func (x *DeleteJobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteJobApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteJobApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobApplicationResponse) Reset() {
	*x = DeleteJobApplicationResponse{}
	mi := &file_api_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobApplicationResponse) ProtoMessage() {}

func (x *DeleteJobApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobApplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteJobApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{7}
}

type JobApplication struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Company       string                  `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Title         string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status        JobApplicationStatus    `protobuf:"varint,4,opt,name=status,proto3,enum=api.v1.JobApplicationStatus" json:"status,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Notes         *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	Cv            *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=cv,proto3" json:"cv,omitempty"`
	CoverLetter   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	AppliedOn     *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=applied_on,json=appliedOn,proto3" json:"applied_on,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobApplication) Reset() {
	*x = JobApplication{}
	mi := &file_api_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplication) ProtoMessage() {}

func (x *JobApplication) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplication.ProtoReflect.Descriptor instead.
func (*JobApplication) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *JobApplication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobApplication) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *JobApplication) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobApplication) GetStatus() JobApplicationStatus {
	if x != nil {
		return x.Status
	}
	return JobApplicationStatus_JOB_APPLICATION_STATUS_UNSPECIFIED
}

func (x *JobApplication) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *JobApplication) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *JobApplication) GetCv() *wrapperspb.StringValue {
	if x != nil {
		return x.Cv
	}
	return nil
}

func (x *JobApplication) GetCoverLetter() *wrapperspb.StringValue {
	if x != nil {
		return x.CoverLetter
	}
	return nil
}

func (x *JobApplication) GetAppliedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.AppliedOn
	}
	return nil
}

func (x *JobApplication) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobApplication) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_v1_api_proto protoreflect.FileDescriptor

const file_api_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x10api/v1/api.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xeb\x02\n" +
	"\x1bCreateJobApplicationRequest\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x122\n" +
	"\x05notes\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12,\n" +
	"\x02cv\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x02cv\x12?\n" +
	"\fcover_letter\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\vcoverLetter\x129\n" +
	"\n" +
	"applied_on\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tappliedOn\"_\n" +
	"\x1cCreateJobApplicationResponse\x12?\n" +
	"\x0fjob_application\x18\x01 \x01(\v2\x16.api.v1.JobApplicationR\x0ejobApplication\"\x1c\n" +
	"\x1aListJobApplicationsRequest\"`\n" +
	"\x1bListJobApplicationsResponse\x12A\n" +
	"\x10job_applications\x18\x01 \x03(\v2\x16.api.v1.JobApplicationR\x0fjobApplications\"\xb1\x03\n" +
	"\x1bUpdateJobApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x122\n" +
	"\x05notes\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12,\n" +
	"\x02cv\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x02cv\x12?\n" +
	"\fcover_letter\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\vcoverLetter\x124\n" +
	"\x06status\x18\b \x01(\x0e2\x1c.api.v1.JobApplicationStatusR\x06status\x129\n" +
	"\n" +
	"applied_on\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tappliedOn\"_\n" +
	"\x1cUpdateJobApplicationResponse\x12?\n" +
	"\x0fjob_application\x18\x01 \x01(\v2\x16.api.v1.JobApplicationR\x0ejobApplication\"-\n" +
	"\x1bDeleteJobApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\x1cDeleteJobApplicationResponse\"\x9a\x04\n" +
	"\x0eJobApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.api.v1.JobApplicationStatusR\x06status\x12>\n" +
	"\vdescription\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x122\n" +
	"\x05notes\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12,\n" +
	"\x02cv\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x02cv\x12?\n" +
	"\fcover_letter\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\vcoverLetter\x129\n" +
	"\n" +
	"applied_on\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tappliedOn\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xc0\x02\n" +
	"\x14JobApplicationStatus\x12&\n" +
	"\"JOB_APPLICATION_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eJOB_APPLICATION_STATUS_APPLIED\x10\x01\x12$\n" +
	" JOB_APPLICATION_STATUS_SCREENING\x10\x02\x12$\n" +
	" JOB_APPLICATION_STATUS_INTERVIEW\x10\x03\x12 \n" +
	"\x1cJOB_APPLICATION_STATUS_OFFER\x10\x04\x12#\n" +
	"\x1fJOB_APPLICATION_STATUS_REJECTED\x10\x05\x12$\n" +
	" JOB_APPLICATION_STATUS_WITHDRAWN\x10\x06\x12#\n" +
	"\x1fJOB_APPLICATION_STATUS_ACCEPTED\x10\a2\x92\x03\n" +
	"\aService\x12a\n" +
	"\x14CreateJobApplication\x12#.api.v1.CreateJobApplicationRequest\x1a$.api.v1.CreateJobApplicationResponse\x12^\n" +
	"\x13ListJobApplications\x12\".api.v1.ListJobApplicationsRequest\x1a#.api.v1.ListJobApplicationsResponse\x12a\n" +
	"\x14UpdateJobApplication\x12#.api.v1.UpdateJobApplicationRequest\x1a$.api.v1.UpdateJobApplicationResponse\x12a\n" +
	"\x14DeleteJobApplication\x12#.api.v1.DeleteJobApplicationRequest\x1a$.api.v1.DeleteJobApplicationResponseB\x13Z\x11kiseki/api/v1;apib\x06proto3"

var (
	file_api_v1_api_proto_rawDescOnce sync.Once
	file_api_v1_api_proto_rawDescData []byte
)

func file_api_v1_api_proto_rawDescGZIP() []byte {
	file_api_v1_api_proto_rawDescOnce.Do(func() {
		file_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_api_proto_rawDesc), len(file_api_v1_api_proto_rawDesc)))
	})
	return file_api_v1_api_proto_rawDescData
}

var file_api_v1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_api_proto_goTypes = []any{
	(JobApplicationStatus)(0),            // 0: api.v1.JobApplicationStatus
	(*CreateJobApplicationRequest)(nil),  // 1: api.v1.CreateJobApplicationRequest
	(*CreateJobApplicationResponse)(nil), // 2: api.v1.CreateJobApplicationResponse
	(*ListJobApplicationsRequest)(nil),   // 3: api.v1.ListJobApplicationsRequest
	(*ListJobApplicationsResponse)(nil),  // 4: api.v1.ListJobApplicationsResponse
	(*UpdateJobApplicationRequest)(nil),  // 5: api.v1.UpdateJobApplicationRequest
	(*UpdateJobApplicationResponse)(nil), // 6: api.v1.UpdateJobApplicationResponse
	(*DeleteJobApplicationRequest)(nil),  // 7: api.v1.DeleteJobApplicationRequest
	(*DeleteJobApplicationResponse)(nil), // 8: api.v1.DeleteJobApplicationResponse
	(*JobApplication)(nil),               // 9: api.v1.JobApplication
	(*wrapperspb.StringValue)(nil),       // 10: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),        // 11: google.protobuf.Timestamp
}
var file_api_v1_api_proto_depIdxs = []int32{
	10, // 0: api.v1.CreateJobApplicationRequest.description:type_name -> google.protobuf.StringValue
	10, // 1: api.v1.CreateJobApplicationRequest.notes:type_name -> google.protobuf.StringValue
	10, // 2: api.v1.CreateJobApplicationRequest.cv:type_name -> google.protobuf.StringValue
	10, // 3: api.v1.CreateJobApplicationRequest.cover_letter:type_name -> google.protobuf.StringValue
	11, // 4: api.v1.CreateJobApplicationRequest.applied_on:type_name -> google.protobuf.Timestamp
	9,  // 5: api.v1.CreateJobApplicationResponse.job_application:type_name -> api.v1.JobApplication
	9,  // 6: api.v1.ListJobApplicationsResponse.job_applications:type_name -> api.v1.JobApplication
	10, // 7: api.v1.UpdateJobApplicationRequest.description:type_name -> google.protobuf.StringValue
	10, // 8: api.v1.UpdateJobApplicationRequest.notes:type_name -> google.protobuf.StringValue
	10, // 9: api.v1.UpdateJobApplicationRequest.cv:type_name -> google.protobuf.StringValue
	10, // 10: api.v1.UpdateJobApplicationRequest.cover_letter:type_name -> google.protobuf.StringValue
	0,  // 11: api.v1.UpdateJobApplicationRequest.status:type_name -> api.v1.JobApplicationStatus
	11, // 12: api.v1.UpdateJobApplicationRequest.applied_on:type_name -> google.protobuf.Timestamp
	9,  // 13: api.v1.UpdateJobApplicationResponse.job_application:type_name -> api.v1.JobApplication
	0,  // 14: api.v1.JobApplication.status:type_name -> api.v1.JobApplicationStatus
	10, // 15: api.v1.JobApplication.description:type_name -> google.protobuf.StringValue
	10, // 16: api.v1.JobApplication.notes:type_name -> google.protobuf.StringValue
	10, // 17: api.v1.JobApplication.cv:type_name -> google.protobuf.StringValue
	10, // 18: api.v1.JobApplication.cover_letter:type_name -> google.protobuf.StringValue
	11, // 19: api.v1.JobApplication.applied_on:type_name -> google.protobuf.Timestamp
	11, // 20: api.v1.JobApplication.created_at:type_name -> google.protobuf.Timestamp
	11, // 21: api.v1.JobApplication.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 22: api.v1.Service.CreateJobApplication:input_type -> api.v1.CreateJobApplicationRequest
	3,  // 23: api.v1.Service.ListJobApplications:input_type -> api.v1.ListJobApplicationsRequest
	5,  // 24: api.v1.Service.UpdateJobApplication:input_type -> api.v1.UpdateJobApplicationRequest
	7,  // 25: api.v1.Service.DeleteJobApplication:input_type -> api.v1.DeleteJobApplicationRequest
	2,  // 26: api.v1.Service.CreateJobApplication:output_type -> api.v1.CreateJobApplicationResponse
	4,  // 27: api.v1.Service.ListJobApplications:output_type -> api.v1.ListJobApplicationsResponse
	6,  // 28: api.v1.Service.UpdateJobApplication:output_type -> api.v1.UpdateJobApplicationResponse
	8,  // 29: api.v1.Service.DeleteJobApplication:output_type -> api.v1.DeleteJobApplicationResponse
	26, // [26:30] is the sub-list for method output_type
	22, // [22:26] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_v1_api_proto_init() }
func file_api_v1_api_proto_init() {
	if File_api_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_api_proto_rawDesc), len(file_api_v1_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_api_proto_goTypes,
		DependencyIndexes: file_api_v1_api_proto_depIdxs,
		EnumInfos:         file_api_v1_api_proto_enumTypes,
		MessageInfos:      file_api_v1_api_proto_msgTypes,
	}.Build()
	File_api_v1_api_proto = out.File
	file_api_v1_api_proto_goTypes = nil
	file_api_v1_api_proto_depIdxs = nil
}
