// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v1/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJobApplicationRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Company       string                  `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Notes         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	Cv            *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=cv,proto3" json:"cv,omitempty"`
	CoverLetter   *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobApplicationRequest) Reset() {
	*x = CreateJobApplicationRequest{}
	mi := &file_api_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobApplicationRequest) ProtoMessage() {}

func (x *CreateJobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateJobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobApplicationRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateJobApplicationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateJobApplicationRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *CreateJobApplicationRequest) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *CreateJobApplicationRequest) GetCv() *wrapperspb.StringValue {
	if x != nil {
		return x.Cv
	}
	return nil
}

func (x *CreateJobApplicationRequest) GetCoverLetter() *wrapperspb.StringValue {
	if x != nil {
		return x.CoverLetter
	}
	return nil
}

type CreateJobApplicationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobApplication *JobApplication        `protobuf:"bytes,1,opt,name=job_application,json=jobApplication,proto3" json:"job_application,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateJobApplicationResponse) Reset() {
	*x = CreateJobApplicationResponse{}
	mi := &file_api_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobApplicationResponse) ProtoMessage() {}

func (x *CreateJobApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateJobApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobApplicationResponse) GetJobApplication() *JobApplication {
	if x != nil {
		return x.JobApplication
	}
	return nil
}

type JobApplication struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Company       string                  `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Title         string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Notes         *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	Cv            *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=cv,proto3" json:"cv,omitempty"`
	CoverLetter   *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobApplication) Reset() {
	*x = JobApplication{}
	mi := &file_api_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplication) ProtoMessage() {}

func (x *JobApplication) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplication.ProtoReflect.Descriptor instead.
func (*JobApplication) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *JobApplication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobApplication) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *JobApplication) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobApplication) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *JobApplication) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *JobApplication) GetCv() *wrapperspb.StringValue {
	if x != nil {
		return x.Cv
	}
	return nil
}

func (x *JobApplication) GetCoverLetter() *wrapperspb.StringValue {
	if x != nil {
		return x.CoverLetter
	}
	return nil
}

func (x *JobApplication) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobApplication) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_v1_api_proto protoreflect.FileDescriptor

const file_api_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x10api/v1/api.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb0\x02\n" +
	"\x1bCreateJobApplicationRequest\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x122\n" +
	"\x05notes\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12,\n" +
	"\x02cv\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x02cv\x12?\n" +
	"\fcover_letter\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\vcoverLetter\"_\n" +
	"\x1cCreateJobApplicationResponse\x12?\n" +
	"\x0fjob_application\x18\x01 \x01(\v2\x16.api.v1.JobApplicationR\x0ejobApplication\"\xa9\x03\n" +
	"\x0eJobApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x122\n" +
	"\x05notes\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12,\n" +
	"\x02cv\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x02cv\x12?\n" +
	"\fcover_letter\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\vcoverLetter\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2l\n" +
	"\aService\x12a\n" +
	"\x14CreateJobApplication\x12#.api.v1.CreateJobApplicationRequest\x1a$.api.v1.CreateJobApplicationResponseB\x13Z\x11kiseki/api/v1;apib\x06proto3"

var (
	file_api_v1_api_proto_rawDescOnce sync.Once
	file_api_v1_api_proto_rawDescData []byte
)

func file_api_v1_api_proto_rawDescGZIP() []byte {
	file_api_v1_api_proto_rawDescOnce.Do(func() {
		file_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_api_proto_rawDesc), len(file_api_v1_api_proto_rawDesc)))
	})
	return file_api_v1_api_proto_rawDescData
}

var file_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_api_proto_goTypes = []any{
	(*CreateJobApplicationRequest)(nil),  // 0: api.v1.CreateJobApplicationRequest
	(*CreateJobApplicationResponse)(nil), // 1: api.v1.CreateJobApplicationResponse
	(*JobApplication)(nil),               // 2: api.v1.JobApplication
	(*wrapperspb.StringValue)(nil),       // 3: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),        // 4: google.protobuf.Timestamp
}
var file_api_v1_api_proto_depIdxs = []int32{
	3,  // 0: api.v1.CreateJobApplicationRequest.description:type_name -> google.protobuf.StringValue
	3,  // 1: api.v1.CreateJobApplicationRequest.notes:type_name -> google.protobuf.StringValue
	3,  // 2: api.v1.CreateJobApplicationRequest.cv:type_name -> google.protobuf.StringValue
	3,  // 3: api.v1.CreateJobApplicationRequest.cover_letter:type_name -> google.protobuf.StringValue
	2,  // 4: api.v1.CreateJobApplicationResponse.job_application:type_name -> api.v1.JobApplication
	3,  // 5: api.v1.JobApplication.description:type_name -> google.protobuf.StringValue
	3,  // 6: api.v1.JobApplication.notes:type_name -> google.protobuf.StringValue
	3,  // 7: api.v1.JobApplication.cv:type_name -> google.protobuf.StringValue
	3,  // 8: api.v1.JobApplication.cover_letter:type_name -> google.protobuf.StringValue
	4,  // 9: api.v1.JobApplication.created_at:type_name -> google.protobuf.Timestamp
	4,  // 10: api.v1.JobApplication.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: api.v1.Service.CreateJobApplication:input_type -> api.v1.CreateJobApplicationRequest
	1,  // 12: api.v1.Service.CreateJobApplication:output_type -> api.v1.CreateJobApplicationResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_v1_api_proto_init() }
func file_api_v1_api_proto_init() {
	if File_api_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_api_proto_rawDesc), len(file_api_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_api_proto_goTypes,
		DependencyIndexes: file_api_v1_api_proto_depIdxs,
		MessageInfos:      file_api_v1_api_proto_msgTypes,
	}.Build()
	File_api_v1_api_proto = out.File
	file_api_v1_api_proto_goTypes = nil
	file_api_v1_api_proto_depIdxs = nil
}
